<?php
$return_string.= $bep_shortcode_1_query->current_post;		
$return_string.="<div class='{$prefix}module_10 {$prefix}module_wrap {$prefix}animation-stack'>";
$return_string.="	<div class='{$prefix}module-thumb'>";
$return_string.="		<a href='" . get_permalink() . "' rel='bookmark' title='".get_the_title()."'>";
$return_string.="			<img width='218' height='150' class='entry-thumb {$prefix}animation-stack-type0-2' src='" . wp_get_attachment_image_src(get_post_thumbnail_id($id), 'bep_shortcodes_2-big', false)[0] . "' alt='' title='". get_the_title() . "'>";
$return_string.="		</a>";
$return_string.="	</div>";
$return_string.="	<div class='item-details'>";
$return_string.="		<h3 class='entry-title {$prefix}module-title'>";
$return_string.="			 <a href='" . get_permalink() . "' rel='bookmark' title='".get_the_title()."'>";
$return_string.="           ".get_the_title()."";
$return_string.="       </a>";
$return_string.="		</h3>";
$return_string.="		<div class='{$prefix}module-meta-info'>";
$return_string.="			<span class='{$prefix}post-author-name'>";
$return_string.="           	<a href='". get_author_posts_url( get_the_ID() ) ."'>";
$return_string.="					".get_the_author() ."";
$return_string.="           	</a>";
$return_string.="				<span>-</span>";
$return_string.="			</span>";   
$return_string.="			<span class='{$prefix}post-date'>";
$return_string.="           <time class='entry-date updated {$prefix}module-date' datetime='". get_the_date('c' , get_the_ID() ) ."'>";
$return_string.="               ". get_the_date('F j,Y' , get_the_ID() ) ."";
$return_string.="           </time>";
$return_string.="			</span>";
$return_string.="		</div>";
$return_string.="		<div class='{$prefix}excerpt'>";
$return_string.="	                    Wednesday, Amazon announced to introduce its online video-on-demand service in Pakistan along with other 200 countries worldwide. Earlier, Amazon Prime Video was available only...";
$return_string.="		</div>";
$return_string.="	</div>";
$return_string.="</div>";
?>